# Generated by Django 5.0.2 on 2024-03-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circlecategory',
            options={'verbose_name': 'Circle Category', 'verbose_name_plural': 'Circle Categories'},
        ),
        migrations.AlterModelOptions(
            name='mainbanner',
            options={'verbose_name': 'Main Banner', 'verbose_name_plural': 'Main Banners'},
        ),
    ]
