# Generated by Django 5.0.2 on 2024-03-12 15:38

import ckeditor_uploader.fields
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '2 Category',
                'verbose_name_plural': '2 Categories',
            },
        ),
        migrations.CreateModel(
            name='SuperCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please write the name in ALL CAPITALS', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, help_text='Please upload an image with dimensions 1080x1080.', null=True, upload_to=inventory.models.get_upload_path)),
            ],
            options={
                'verbose_name': '1 Super Category',
                'verbose_name_plural': '1 Super Categories',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ManyToManyField(blank=True, to='inventory.category')),
                ('super_categories', models.ManyToManyField(to='inventory.supercategory')),
            ],
            options={
                'verbose_name': '3 Sub Category',
                'verbose_name_plural': '3 Sub Categories',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='super_category',
            field=models.ManyToManyField(blank=True, to='inventory.supercategory'),
        ),
    ]
