name: Django Github Action

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.4

            - name: Setup Python Version
              uses: actions/setup-python@v5.1.0
              with: 
                python-version: 3.12

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Lint with Flake8
              run: |
                flake8 .

            - name: Run tests
              run: |
                python manage.py test

            - name: Deploy to EC2
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                  sudo -i
                  cd /home/projectcicd/aawscicd
                  ./deploy.sh

            # After deploy.sh completes, check the exit code and proceed accordingly
            - name: Check deployment status
              if: ${{ job.status == 'success' }}
              run: echo "Deployment completed successfully"
          
            - name: Handle deployment failure
              if: ${{ job.status != 'success' }}
              run: echo "Deployment failed"

